version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    restart: always
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - internal

  php-fpm:
    build:
        context: docker/php-fpm
    container_name: php-fpm
    volumes:
      - ./:/var/www
    restart: always
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.100.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

networks:
  internal:
    driver: bridge